//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyVersion("2.0.00424.2")]
[assembly: AssemblyFileVersion("2.0.00424.2")]

// Generated by the MSBuild WriteCodeFragment class on 4/24/2013 12:50:30 PM.

